apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: prometheus 
  namespace: config-management-system
spec:
  sourceType: helm
  sourceFormat: unstructured
  helm:
    repo: https://prometheus-community.github.io/helm-charts 
    chart: kube-prometheus-stack 
    version: 40.0.0 
    releaseName: kube-prometheus
    namespace: monitoring-infra 
    values:
      grafana:
        adminPassword: seokbin
    auth: none
