apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: teleport 
  namespace: config-management-system
spec:
  sourceType: git 
  sourceFormat: unstructured
  git:
    repo: https://github.com/Goseokbin/my-configsync.git 
    branch: main
    dir: teleport 
    auth: token
    secretRef:
      name: github-token
