---
# Source: teleport-kube-agent/templates/delete_hook.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: configsync-teleport-delete-hook
  namespace: configsync-teleport
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
# Source: teleport-kube-agent/templates/delete_hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configsync-teleport-delete-hook
  namespace: configsync-teleport
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["secrets",]
    verbs: ["get", "delete", "list"]
---
# Source: teleport-kube-agent/templates/delete_hook.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configsync-teleport-delete-hook
  namespace: configsync-teleport
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configsync-teleport-delete-hook
subjects:
- kind: ServiceAccount
  name: configsync-teleport-delete-hook
  namespace: configsync-teleport
---
# Source: teleport-kube-agent/templates/delete_hook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: configsync-teleport-delete-hook
  namespace: configsync-teleport
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: configsync-teleport-delete-hook
    spec:
      serviceAccountName: configsync-teleport-delete-hook
      restartPolicy: OnFailure
      containers:
      - name: post-delete-job
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: RELEASE_NAME
            value: configsync-teleport
        image: "public.ecr.aws/gravitational/teleport-distroless:14.0.0-dev"
        imagePullPolicy: IfNotPresent
        command: ["teleport"]
        args: ["kube-state", "delete"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 9807
