---
# Source: teleport-kube-agent/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configsync-teleport
  namespace: configsync-teleport
data:
  teleport.yaml: |
    app_service:
      enabled: false
    auth_service:
      enabled: false
    db_service:
      enabled: false
    kubernetes_service:
      enabled: true
      kube_cluster_name: configsync-teleport
    proxy_service:
      enabled: false
    ssh_service:
      enabled: false
    teleport:
      join_params:
        method: token
        token_name: /etc/teleport-secrets/auth-token
      log:
        format:
          extra_fields:
          - timestamp
          - level
          - component
          - caller
          output: text
        output: stderr
        severity: INFO
      proxy_server: teleport.develop.matilda-mzc.com:443
    version: v3
