---
# Source: teleport-kube-agent/templates/deployment.yaml
#
# Warning to maintainers, any changes to this file that are not specific to the Deployment need to also be duplicated
# in the statefulset.yaml file.
#
