---
# Source: teleport-kube-agent/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configsync-teleport
  namespace: configsync-teleport
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configsync-teleport
subjects:
- kind: ServiceAccount
  name: configsync-teleport
  namespace: configsync-teleport
