resources:  
- ../base
patches:
- target:
    kind: Ingress
    name: kube-prometheus-stack-grafana 
  patch: |-
    - op : replace
      path: /spec/rules/hosts
      value: monitoring.tanzu.matilda-mzc.com
