bases:
  - ../base
helmCharts:
- name: kube-prometheus-stack 
  repo: https://prometheus-community.github.io/helm-charts 
  version: v45.23.0
  releaseName: kube-prometheus-stack 
  namespace: monitoring
  valuesInline:
    grafana:
      ingress:
      hosts:
      - monitoring.tanzu.matilda-mzc.com 
  valuesMerge: merge
